version: "3.2"
services:
  client:
    image: node:10.13.0-alpine
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./client
        target: /app

  server:
    image: node:10.13.0-alpine
    working_dir: /app
    ports:
      - "5000:5000"
    command: npm run dev:server
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./docker/mongo
        target: /data/db



